import math
a = round(317.5)
print(a)
b = round(-1.5)
print(b)
c = round(-2.675, 2)
print(c)
d = math.floor(1.5)
print(d)
e = math.ceil(2.1)
print(e)
f = math.pi
print(f)
g = math.e
print(g)
h = math.sin(math.pi/2)
print(h)
i = math.sin(math.pi)
print(i)
j = math.floor(math.sin(math.pi))
print(j)
k = math.sin(0)
print(k)
l = math.acos(0)
print(l)
m = math.asin(0)
print(m)
o = math.hypot(3,4)
print(0)
p = math.pow(2,3)
print(p)
print(2 ** 3)
print(math.pow(9,2))
print(9 ** 2)
print(math.exp(2))
print(math.log(math.e))
print(math.log2(32))
print(math.log10(1000))

